# Generated by Django 5.0.7 on 2024-07-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='file',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='description',
        ),
    ]
