# Generated by Django 5.0.7 on 2024-08-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_cart_cartitem_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='catalog.CartItem', to='catalog.product'),
        ),
    ]
